## Odin1 数据流控制文件

register_keys:
  # 如果关闭此项，即使USB连接低于3.0版本，也允许进行连接
  # ATTENTION: 始终推荐使用USB 3.0，因为SLAM模式等高级功能需要USB 3.0来确保地图文件传输的可靠性
  strict_usb3.0_check: 1  # 0:关闭 || 1:开启

  # 0: 使用Odin内部系统时间作为数据时间戳，这是典型做法，也是推荐设置
  # 1: 使用主机ROS时间（以收到数据的时间为准）作为数据时间戳，仅在你有特殊需求时使用，对绝大多数用户不推荐
  use_host_ros_time: 0

  streamctrl: 1           # 0:关闭 || 1:开启

  # 来自设备的原始RGB数据将以JPEG格式（压缩格式）发送
  sendrgbcompressed: 1    # 0:关闭 || 1:开启

  # RGB数据，由来自 Odin1 设备的原始JPEG数据解码而来，采用bgr8格式,此过程发生在主机设备上
  sendrgb: 1              # 0:关闭 || 1:开启

  # 对解码后的RGB数据进行去畸变（校正）处理
  # 该功能依赖于 sendrgb 是否开启，相关的相机内参和畸变参数可以在 ws/src/odin_ros_driver/config/calib.yaml 文件中找到
  # 此过程发生在主机设备上
  sendrgbundistort: 1     # 0:关闭 || 1:开启

  # IMU data
  sendimu: 1              # 0:关闭 || 1:开启

  # Odometry data
  sendodom: 1             # 0:关闭 || 1:开启

  # 发布从odom坐标系到base_link坐标系的TF变换，除非你有明确的特殊需求要关闭它，否则请保持开启状态
  # ATTENTION: 这对于在RViz中显示cloud_raw至关重要
  send_odom_baselink_tf: 1 # 0:关闭 || 1:开启

  # raw dtof data
  senddtof: 1             # 0:关闭 || 1:开启

  # slam cloud data
  sendcloudslam: 1        # 0:关闭 || 1:开启

  # 利用来自设备的原始点云（raw point cloud）、RGB 图像以及标定文件（calib.yaml）进行处理
  # 此过程发生在主机设备上
  sendcloudrender: 1      # 0:关闭 || 1:开启

  # 深度补全（Depth Completion）示例演示，计算资源占用率高
  # 如需了解更多信息，请参阅 README 文件
  # 此过程发生在主机设备上
  senddepth: 1            # 0:关闭 || 1:开启

  # 将RGB图像、里程计（Odometry）以及SLAM点云数据录制并保存为 .olx 私有格式，以便后续在MindCloud(TM)软件中进行进一步处理 
  # save path: ws/src/odin_ros_driver/recorddata/{record_start_time}/
  # ATTENTION: 后期处理时，请务必拷贝整个文件夹
  recorddata: 0           # 0:关闭 || 1:开启

  # 将设备运行时状态信息保存至路径 ws/src/odin_ros_driver/log/Driver_{drvier_start_time}/Conn_{device_connection_time}/dev_status.csv
  devstatuslog: 1         # 0:关闭 || 1:开启

  save_log: 0             # 0:关闭 || 1:开启

  # 灰度格式的原始dToF传感器强度（Intensity）数据，主要用于调试目的
  pubintensitygray: 0     # 0:关闭 || 1:开启

  showpath: 0             # 0:关闭 || 1:开启
  showcamerapose: 0       # 0:关闭 || 1:开启
  
  custom_map_mode: 0      # 0: Odometry mode 1: SLAM mode 2: Relocalization mode

  custom_save_map: 0
  custom_init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  
  relocalization_map_abs_path: ""    # must be set for Relocalization mode or will fail
  mapping_result_dest_dir: ""        # "": use default value; other: use custom value
  mapping_result_file_name: ""       # "": use default value; other: use custom value 
